AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Resources:
  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 300
      Environment:
        Variables:
          ALEXA_APP_ID: !Ref ParamAlexaAppId
          TWITTER_CONSUMER_KEY: !Ref ParamTwitterConsumerKey
          TWITTER_API_SECRET: !Ref ParamTwitterApiSecret
          RESTAPI_ID: !Ref ParamRestApiId
          RESTAPI_REGION: !Ref ParamRestApiRegion
          RESTAPI_STAGE: !Ref ParamRestApiStage
          OVERRIDE_RESTAPI_URI: override_restapi_uri
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill

Parameters:
  ParamAlexaAppId:
    Type: String
  ParamTwitterConsumerKey:
    Type: String
  ParamTwitterApiSecret:
    Type: String
  ParamRestApiId:
    Type: String
  ParamRestApiRegion:
    Type: String
  ParamRestApiStage:
    Type: String